version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - mvn package -DskipTests=true --batch-mode --quiet
      - aws cloudformation package --template template.yml --s3-bucket tesis-licenciatura-artifacts --output-template template-export.yml
      - aws cloudformation deploy --template-file template-export.yml --stack-name tesis-licenciatura-stack --capabilities CAPABILITY_NAMED_IAM
artifacts:
  discard-paths: yes
  files:
    - template-export.yml
cache:
  paths:
    - '/root/.m2/**/*'
