version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      # build
      - mvn package -DskipTests=true --batch-mode --quiet
      # upload artifacts
#      - aws s3 cp servicios-ficticios-terceros/eafg-consulta/target/eafg-consulta-1.0-SNAPSHOT.jar s3://tesis-licenciatura-artifacts/
#      - mv servicios-ficticios-terceros/eafg-pago/target/eafg-pago-1.0-SNAPSHOT.jar s3://tesis-licenciatura-artifacts/
#      - mv servicios-ficticios-terceros/eefg-consulta/target/eefg-consulta-1.0-SNAPSHOT.jar s3://tesis-licenciatura-artifacts/
#      - mv servicios-ficticios-terceros/eefg-pago/target/eefg-pago-1.0-SNAPSHOT.jar s3://tesis-licenciatura-artifacts/
#      - mv servicios-ficticios-terceros/etfg-consulta/target/etfg-consulta-1.0-SNAPSHOT.jar s3://tesis-licenciatura-artifacts/
#      - mv servicios-ficticios-terceros/etfg-pago/target/etfg-pago-1.0-SNAPSHOT.jar s3://tesis-licenciatura-artifacts/
#      - mv arquitectura-serverless/buscar-servicio/target/buscar-servicio-1.0-SNAPSHOT.jar s3://tesis-licenciatura-artifacts/
#      - mv arquitectura-serverless/listar-cuentas/target/listar-cuentas-1.0-SNAPSHOT.jar s3://tesis-licenciatura-artifacts/
#      - mv arquitectura-serverless/obtener-identificadores/target/obtener-identificadores-1.0-SNAPSHOT.jar s3://tesis-licenciatura-artifacts/
      # upload templates
#      - aws s3 cp servicios-ficticios-terceros/functions.yml s3://tesis-licenciatura-artifacts/servicios-ficticios-terceros-functions.yml
#      - aws s3 cp servicios-ficticios-terceros/functions.yml s3://tesis-licenciatura-artifacts/servicios-ficticios-terceros-api.yml
#      - aws s3 cp arquitectura-serverless/functions.yml s3://tesis-licenciatura-artifacts/arquitectura-serverless-functions.yml
#      - aws s3 cp arquitectura-serverless/functions.yml s3://tesis-licenciatura-artifacts/arquitectura-serverless-api.yml
      # cloudformation deploy
      - aws cloudformation package --template template.yml --s3-bucket tesis-licenciatura-artifacts --output-template template-export.yml
      - aws cloudformation deploy --template-file template-export.yml --stack-name tesis-licenciatura-stack --capabilities CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND
artifacts:
  discard-paths: yes
  files:
    - template-export.yml
cache:
  paths:
    - '/root/.m2/**/*'
