version: 0.2

phases:
  build:
    commands:
      - mvn package
      - mkdir tmp
      - mv servicios-ficticios-terceros/eafg-consulta/target/eafg-consulta-1.0-SNAPSHOT.jar tmp/eafg-consulta.jar
      - mv servicios-ficticios-terceros/eafg-pago/target/eafg-pago-1.0-SNAPSHOT.jar tmp/eafg-pago.jar
      - mv servicios-ficticios-terceros/eefg-consulta/target/eefg-consulta-1.0-SNAPSHOT.jar tmp/eefg-consulta.jar
      - mv servicios-ficticios-terceros/eefg-pago/target/eefg-pago-1.0-SNAPSHOT.jar tmp/eefg-pago.jar
      - mv servicios-ficticios-terceros/etfg-consulta/target/etfg-consulta-1.0-SNAPSHOT.jar tmp/etfg-consulta.jar
      - mv servicios-ficticios-terceros/etfg-pago/target/etfg-pago-1.0-SNAPSHOT.jar tmp/etfg-pago.jar
      - mv template-configuration.json tmp/template-configuration.json
      - mv template.yml tmp/template.yml
      - cd tmp
      - aws cloudformation package --template template.yml --s3-bucket tesis-licenciatura-artifacts --output-template template-export.yml
      - cd ..
artifacts:
  discard-paths: yes
  files:
    - tmp/template-export.yml
    - tmp/template-configuration.json
cache:
  paths:
    - '/root/.m2/**/*'