version: 0.2

phases:
  build:
    commands:
      - mvn clean && mvn install
      - aws cloudformation deploy --template-file ./app.yml --stack-name tesis-licenciatura-stack
artifacts:
  discard-paths: yes
  files:
    - servicios-ficticios-terceros/eafg-consulta/target/eafg-consulta-1.0-SNAPSHOT.jar
    - servicios-ficticios-terceros/eafg-pago/target/eafg-pago-1.0-SNAPSHOT.jar
    - servicios-ficticios-terceros/eefg-consulta/target/eefg-consulta-1.0-SNAPSHOT.jar
    - servicios-ficticios-terceros/eefg-pago/target/eefg-pago-1.0-SNAPSHOT.jar
    - servicios-ficticios-terceros/etfg-consulta/target/etfg-consulta-1.0-SNAPSHOT.jar
    - servicios-ficticios-terceros/etfg-pago/target/etfg-pago-1.0-SNAPSHOT.jar
cache:
  paths:
    - '/root/.m2/**/*'