AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Tesis Licenciatura

Resources:
  ApiStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./arquitectura-serverless/api.yml
  FunctionsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./arquitectura-serverless/functions.yml
  ApiSFTStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./servicios-ficticios-terceros/api.yml
  FunctionsSFTStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./servicios-ficticios-terceros/functions.yml
