AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Tesis Licenciatura

Resources:
# SERVERLESS
  FunctionsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: arquitectura-serverless/functions.yml
      Parameters:
        Prefix: !Sub "${AWS::StackName}"
  ApiStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: arquitectura-serverless/api.yml
      Parameters:
        Prefix: !Sub "${AWS::StackName}"
      DependsOn:
        - FunctionsStack

# SFT
  FunctionsSFTStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: servicios-ficticios-terceros/functions.yml
      Parameters:
        Prefix: !Sub "${AWS::StackName}"
  ApiSFTStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: servicios-ficticios-terceros/api.yml
      Parameters:
        Prefix: !Sub "${AWS::StackName}"
      DependsOn:
        - FunctionsSFTStack
