AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Tesis Licenciatura
Resources:
  eafgConsulta:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: eafg-consulta
      Handler: com.github.marvindaviddiaz.Servicio
      Runtime: java8
      CodeUri: ./eafg-consulta.jar
      Description: Consulta de Agua
      Timeout: 30
      MemorySize: 128
#      Environment:
#        Variables:
#          RDS_HOSTNAME: betsrds.ckcok406xu5a.us-west-2.rds.amazonaws.com:3006
#          RDS_DB_NAME: Bets
#          RDS_USERNAME: master
#          RDS_PASSWORD: master123
      Role:
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn
      Events:
        PostEvent:
          Type: Api
          Properties:
            Path: /eafg/consulta/
            Method: post

  LambdaExecutionRole:
    Description: Creating service role in IAM for AWS Lambda
    Type: AWS::IAM::Role
    Properties:
      RoleName: 'LambdaExecutionRole'
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [lambda.amazonaws.com]
            Action: sts:AssumeRole
      Path: /eafg/consulta/
      ManagedPolicyArns:
        -  arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
#      PermissionsBoundary: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/CodeStar_${ProjectId}_PermissionsBoundary'


