AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Tesis Licenciatura

Resources:
## SERVERLESS
  FunctionsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: arquitectura-serverless/functions.yml
      Parameters:
        Prefix: !Sub "${AWS::StackName}"
  ApiStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: arquitectura-serverless/api.yml
      Parameters:
        Prefix: !Sub "${AWS::StackName}"
        buscarServicioArn: !GetAtt FunctionsStack.Outputs.buscarServicioArn
        listarCuentasArn: !GetAtt FunctionsStack.Outputs.listarCuentasArn
        obtenerIdentificadoresArn: !GetAtt FunctionsStack.Outputs.obtenerIdentificadoresArn
        consultaArn: !GetAtt FunctionsStack.Outputs.consultaArn
        pagoArn: !GetAtt FunctionsStack.Outputs.pagoArn
        guardarFavoritoArn: !GetAtt FunctionsStack.Outputs.guardarFavoritoArn
        obtenerFavoritosArn: !GetAtt FunctionsStack.Outputs.obtenerFavoritosArn

# SFT
  FunctionsSFTStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: servicios-ficticios-terceros/functions.yml
      Parameters:
        Prefix: !Sub "${AWS::StackName}"
  ApiSFTStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: servicios-ficticios-terceros/api.yml
      Parameters:
        Prefix: !Sub "${AWS::StackName}"
        eafgConsultaArn: !GetAtt FunctionsSFTStack.Outputs.eafgConsultaArn
        eafgPagoArn: !GetAtt FunctionsSFTStack.Outputs.eafgPagoArn
        eefgConsultaArn: !GetAtt FunctionsSFTStack.Outputs.eefgConsultaArn
        eefgPagoArn: !GetAtt FunctionsSFTStack.Outputs.eefgPagoArn
        etfgConsultaArn: !GetAtt FunctionsSFTStack.Outputs.etfgConsultaArn
        etfgPagoArn: !GetAtt FunctionsSFTStack.Outputs.etfgPagoArn
