AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Tesis Licenciatura

Parameters:
  Prefix:
    Description: Prefix (without spaces)
    Type: String
  eafgConsultaArn:
    Type: String
  eafgPagoArn:
    Type: String
  eefgConsultaArn:
    Type: String
  eefgPagoArn:
    Type: String
  etfgConsultaArn:
    Type: String
  etfgPagoArn:
    Type: String

Resources:

#  VpcEndpointTercerosApi:
#    Type: AWS::EC2::VPCEndpoint
#    Properties:
#      PolicyDocument: '{
#        "Version":"2012-10-17",
#        "Statement":[{
#        "Effect":"Allow",
#        "Principal": "*",
#        "Action":["*"],
#        "Resource":["*"]
#        }]
#      }'
#      PrivateDnsEnabled: true
#      SecurityGroupIds:
#        - sg-877d0ee2
#      ServiceName: com.amazonaws.us-east-1.execute-api
#      SubnetIds:
#        - subnet-a30268c6
#        - subnet-fad6ecd2
#      VpcEndpointType: Interface
#      VpcId: vpc-952bf3f0

  ServerlessTercerosApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: servicios-ficticios-terceros
      StageName: dev
#      EndpointConfiguration: PRIVATE
      DefinitionUri: ./swagger.yml

  #################
  ######## PERMISSIONS
  #################

  eafgConsultaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Sub ${eafgConsultaArn}
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ServerlessTercerosApi}/*/*/*"

  eafgPagoPermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !Sub ${eafgPagoArn}
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ServerlessTercerosApi}/*/*/*"

  eefgConsultaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Sub ${eefgConsultaArn}
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ServerlessTercerosApi}/*/*/*"

  eefgPagoPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Sub ${eefgPagoArn}
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ServerlessTercerosApi}/*/*/*"

  etfgConsultaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Sub ${etfgConsultaArn}
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ServerlessTercerosApi}/*/*/*"

  etfgPagoPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Sub ${etfgPagoArn}
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ServerlessTercerosApi}/*/*/*"
