AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Tesis Licenciatura

Globals:
  Function:
    Runtime: java11
    Timeout: 30
    MemorySize: 256
    Tracing: Active
    Tags:
      bill: tesis

Resources:
  RoleForLambdasSFT:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -   Effect: "Allow"
              Principal:
                Service: "lambda.amazonaws.com"
              Action: "sts:AssumeRole"
          -   Effect: "Allow"
              Principal:
                Service: "apigateway.amazonaws.com"
              Action: "sts:AssumeRole"
      Policies:
        - PolicyName: XRayPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: ['xray:PutTraceSegments', 'xray:PutTelemetryRecords']
                Resource: '*'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole

#################
######## LAMBDAS
#################

  eafgConsulta:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: eafg-consulta
      Handler: com.github.marvindaviddiaz.Servicio
      CodeUri: ./eafg-consulta/target/eafg-consulta-1.0-SNAPSHOT.jar
      Description: Consulta de Agua
      Role: !GetAtt RoleForLambdasSFT.Arn

  eafgPago:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: eafg-pago
      Handler: com.github.marvindaviddiaz.Servicio
      CodeUri: ./eafg-pago/target/eafg-pago-1.0-SNAPSHOT.jar
      Description: Pago de Agua
      Role: !GetAtt RoleForLambdasSFT.Arn

  eefgConsulta:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: eefg-consulta
      Handler: com.github.marvindaviddiaz.Servicio
      CodeUri: ./eefg-consulta/target/eefg-consulta-1.0-SNAPSHOT.jar
      Description: Consulta de Electricidad
      Role: !GetAtt RoleForLambdasSFT.Arn

  eefgPago:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: eefg-pago
      Handler: com.github.marvindaviddiaz.Servicio
      CodeUri: ./eefg-pago/target/eefg-pago-1.0-SNAPSHOT.jar
      Description: Pago de Electricidad
      Role: !GetAtt RoleForLambdasSFT.Arn

  etfgConsulta:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: etfg-consulta
      Handler: com.github.marvindaviddiaz.Servicio
      CodeUri: ./etfg-consulta/target/etfg-consulta-1.0-SNAPSHOT.jar
      Description: Consulta de Teléfono
      Role: !GetAtt RoleForLambdasSFT.Arn

  etfgPago:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: etfg-pago
      Handler: com.github.marvindaviddiaz.Servicio
      CodeUri: ./etfg-pago/target/etfg-pago-1.0-SNAPSHOT.jar
      Description: Pago de Teléfono
      Role: !GetAtt RoleForLambdasSFT.Arn


Outputs:
  eafgConsulta:
    Value: !Ref eafgConsulta
  eafgPago:
    Value: !Ref eafgPago
  eefgConsulta:
    Value: !Ref eefgConsulta
  eefgPago:
    Value: !Ref eefgPago
  etfgConsulta:
    Value: !Ref etfgConsulta
  etfgPago:
    Value: !Ref etfgPago
