AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Tesis Licenciatura

Parameters:
  Prefix:
    Description: Prefix (without spaces)
    Type: String

Globals:
  Function:
    Runtime: java11
    Timeout: 30
    MemorySize: 256
    Tracing: Active
    Tags:
      bill: tesis
    Environment:
      Variables:
        RDS_ENDPOINT: /Tesis/BD/host
        RDS_DB_NAME: /Tesis/BD/name
        RDS_USERNAME: /Tesis/BD/user
        RDS_PASSWORD: /Tesis/BD/password

Resources:
  RoleForLambdas:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -   Effect: "Allow"
              Principal:
                Service: "lambda.amazonaws.com"
              Action: "sts:AssumeRole"
          -   Effect: "Allow"
              Principal:
                Service: "apigateway.amazonaws.com"
              Action: "sts:AssumeRole"
      Policies:
        - PolicyName: GetParametersSystemManagerPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 'ssm:GetParameter'
                Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/Tesis/BD/*'
        - PolicyName: DecryptParametersSystemManagerPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 'kms:Decrypt'
                Resource: !Sub 'arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/d7487d9a-9099-4a31-992a-b704d9f00ab4'
        - PolicyName: XRayPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: ['xray:PutTraceSegments', 'xray:PutTelemetryRecords']
                Resource: '*'

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole

  #################
  ######## LAMBDAS
  #################

  buscarServicio:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: buscar-servicio
      Handler: com.github.marvindaviddiaz.ServicioService
      CodeUri: ./buscar-servicio/target/buscar-servicio-1.0-SNAPSHOT.jar
      Description: Buscar Servicio
      Role: !GetAtt RoleForLambdas.Arn
      VpcConfig:
        SecurityGroupIds:
          - sg-0b2c9b4bfdded5eaf
        SubnetIds:
          - subnet-73dbc135
          - subnet-84e018f3

  listarCuentas:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: listar-cuentas
      Handler: com.github.marvindaviddiaz.CuentaService
      CodeUri: ./listar-cuentas/target/listar-cuentas-1.0-SNAPSHOT.jar
      Description: Listar Cuentas
      Role: !GetAtt RoleForLambdas.Arn
      VpcConfig:
        SecurityGroupIds:
          - sg-0b2c9b4bfdded5eaf
        SubnetIds:
          - subnet-73dbc135
          - subnet-84e018f3


  obtenerIdentificadores:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: obtener-identificadores
      Handler: com.github.marvindaviddiaz.IdentificadorService
      CodeUri: ./obtener-identificadores/target/obtener-identificadores-1.0-SNAPSHOT.jar
      Description: Obtener Identificadores
      Role: !GetAtt RoleForLambdas.Arn
      VpcConfig:
        SecurityGroupIds:
          - sg-0b2c9b4bfdded5eaf
        SubnetIds:
          - subnet-73dbc135
          - subnet-84e018f3

Outputs:
  buscarServicioArn:
    Value: !GetAtt buscarServicio.Arn
    Export:
      Name: !Sub "${Prefix}-buscarServicioArn"
  listarCuentasArn:
    Value: !GetAtt listarCuentas.Arn
    Export:
      Name: !Sub "${Prefix}-listarCuentasArn"
  obtenerIdentificadoresArn:
    Value: !GetAtt obtenerIdentificadores.Arn
    Export:
      Name: !Sub "${Prefix}-obtenerIdentificadoresArn"
